# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77d3a7661bb8e1d60f3c3b6340239a922b458e9289e524f37fa729538d76bb135795ecb50258a6d6bdbf01937110b4c308e6b299da012aada8d72c7b0de31e39

test:
  secret_key_base: 3fde7e588487d2279cd7b73ce423cabd7a36993eb9965c2e66f08934649461e120fccce88e2e64c778453c519c209ddd3d83ef7c4f53ded8bc3bb30a96256eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
